### ISSUE TITLE
Error occurred during project run

### ISSUE THREAD

**Issue by shubham12tomar** [a-nau/Plane-Segmentation-Refinement#1]
I am facing following error after run the command: 
!python run_refinement.py --dir_data ./input/0_dataset_027 --config ./config.yaml

2021-06-06 04:35:05 [INFO]: Loading config from ./config.yaml
WARNING: The following keys specified in input file were not automatically saved in the config: ['file_name_plane_mask_suf', 'file_name_planercnn_image_suf']
2021-06-06 04:35:05 [INFO]: Loading data from ./input/0_dataset_027
2021-06-06 04:35:06 [INFO]: Starting refinement procedure
2021-06-06 04:35:06 [INFO]: ################################### Running on plane 0 ###################################
2021-06-06 04:35:06 [INFO]: Computing lines with Hough Transformation
2021-06-06 04:35:06 [INFO]: Computing lines with clustering
Traceback (most recent call last):
  File "run_refinement.py", line 45, in <module>
    main(args.dir_data, args.config)
  File "run_refinement.py", line 39, in main
    result_dict = start_refinement_procedure(image_data)
  File "/content/Plane-Segmentation-Refinement/refiner/refinement_handler.py", line 29, in start_refinement_procedure
    refined_masks = compute_refined_masks(data)
  File "/content/Plane-Segmentation-Refinement/refiner/refinement_handler.py", line 55, in compute_refined_masks
    mask, lines = compute_refined_mask_and_lines(data.img, data.edge_img, mask, dir_results, i)
  File "/content/Plane-Segmentation-Refinement/refiner/refinement_handler.py", line 89, in compute_refined_mask_and_lines
    output_directory=os.path.join(dir_results, cfg.dir_result_details)
  File "/content/Plane-Segmentation-Refinement/refiner/clustering/handler.py", line 40, in get_lines_from_clustering
    output_directory
  File "/content/Plane-Segmentation-Refinement/refiner/clustering/line_detection.py", line 34, in compute_lines_from_edge_candidate_clusters
    output_directory)
  File "/content/Plane-Segmentation-Refinement/refiner/clustering/line_detection.py", line 58, in find_line_masked_image
    line_mask = cv2.line(line_mask, pt_start, pt_end, tuple([255]), thickness=15)
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 1 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 1 has a wrong type

**Comment by shubham12tomar** [comment]
No Need, I have solved it.
We don't need to install requirements.txt on Google Colab.
If we do it gives us above error.
So skip this step.
